CI: Exclude Python3.12 + MPI

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -12,69 +12,69 @@ jobs:
     runs-on: ubuntu-22.04
 
     steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-        submodules: recursive
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          submodules: recursive
 
-    - name: Installing Python
-      run: |
-        sudo apt-get update -qy
-        sudo apt-get install -y \
-          python3-dev \
-          python3-pip \
-          python3-venv \
-          meson \
-          ninja-build
-        python3 -m venv ../venv
-        source ../venv/bin/activate
-        pip install build
+      - name: Installing Python
+        run: |
+          sudo apt-get update -qy
+          sudo apt-get install -y \
+            python3-dev \
+            python3-pip \
+            python3-venv \
+            meson \
+            ninja-build
+          python3 -m venv ../venv
+          source ../venv/bin/activate
+          pip install build
 
-    - name: Build package
-      run: |
-        source ../venv/bin/activate
-        python3 -m build . -s
+      - name: Build package
+        run: |
+          source ../venv/bin/activate
+          python3 -m build . -s
 
-    - name: Install extension module
-      run: |
-        source ../venv/bin/activate
-        pip install dist/*.tar.gz
+      - name: Install extension module
+        run: |
+          source ../venv/bin/activate
+          pip install dist/*.tar.gz
 
-    - name: Install sphinx
-      run: |
-        source ../venv/bin/activate
-        pip install sphinx sphinx_rtd_theme
+      - name: Install sphinx
+        run: |
+          source ../venv/bin/activate
+          pip install sphinx sphinx_rtd_theme
 
-    - name: Build documentation
-      run: |
-        source ../venv/bin/activate
-        cd docs
-        sphinx-apidoc -o source/ ../SurfaceTopography
-        make html
-        cd ..
+      - name: Build documentation
+        run: |
+          source ../venv/bin/activate
+          cd docs
+          sphinx-apidoc -o source/ ../SurfaceTopography
+          make html
+          cd ..
 
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/ContactEngineering/SurfaceTopography.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/ContactEngineering/SurfaceTopography.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
 
-    - name: Push documentation changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Push documentation changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Publish package
-      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
-      uses: pypa/gh-action-pypi-publish@master
-      with:
-        user: __token__
-        password: ${{ secrets.PYPI_PASSWORD }}
+      - name: Publish package
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
+        uses: pypa/gh-action-pypi-publish@master
+        with:
+          user: __token__
+          password: ${{ secrets.PYPI_PASSWORD }}
